# DataSource Config
spring:
  datasource:
    url: jdbc:mysql://liuyuncen.com:3388/cloud
    username: cloud
    password: cloud
server:
  port: 8080

mybatis-flex:
  configuration:
    ## 显示执行的SQL信息
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
